version: '3.4'

services:
    
    postgresql:
        image: postgres:latest
        environment:
            - POSTGRES_USER=miraz
            - POSTGRES_PASSWORD=miraz
            - POSTGRES_DB=fishery_management
        ports: 
            - "5434:5432"
        restart: always
        volumes: 
            - database-data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=miraz@miraz.com
            - PGADMIN_DEFAULT_PASSWORD=miraz
        ports:
            - '5000:80'
        restart: always
        volumes: 
            - pgadmin:/root/.pgadmin
    app:
      container_name: "fishery"
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./src:/app/src
      ports:
        - 8010:8000
      env_file:
        - .env
volumes:
    database-data:
    pgadmin: