FROM python:3.8-slim
 
ENV PYTHONUNBUFFERED 1
 
WORKDIR /app
RUN mkdir src
 
RUN pip install -U pip
ADD requirements.txt /app
RUN pip install -r requirements.txt
 
COPY src/ /app/src/

CMD ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]

 
EXPOSE 8000
